  ####################################################################################################
  ## Manage Firewall Rules ###########################################################################
  ####################################################################################################
    - name: Manage Firewall Rules
      vmware_host_firewall_manager:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}"  ## This is used if running against machine cluster instead of stand alone ESXI
        validate_certs: no      
        rules:
          - name: DHCPv6
            enabled: False
          - name: iSCSI
            enabled: False
          - name: snmp 
            enabled: False