####################################################################################################
## This is used for patching Debian Systems ######################################################## 
####################################################################################################

- hosts: all 
  gather_facts: false
  serial: 1  ## This performs the playbook in series on the host specified in the inventor

####################################################################################################
## Ansible Roles to perform ######################################################## 
####################################################################################################

  roles:
   - apt-get_update
   - apt-get_upgrade
