- hosts: localhost 
  gather_facts: no
  strategy: free
  ####################################################################################################
  ## Variables #######################################################################################
  ####################################################################################################

  vars:
    vcenter_hostname: bennetvc.bennet.com 
    vcenter_username: bwalker@bennet.com 
    esxi_hostname: bennetesxi.bennet.com
    esxi_username: root



  tasks:

  ####################################################################################################
  ## Gathering Facts #################################################################################
  ####################################################################################################

    - name: Get Services
      vmware_host_service_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
      tags: debug

    - name: Get Advanced Options
      vmware_host_config_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
      tags: debug

    - name: Get Firewall Rules
      vmware_host_firewall_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}"  
        validate_certs: no
      tags: debug

  ####################################################################################################
  ## Disable Lockdown Mode ############################################################################
  ####################################################################################################

    - name: Disable Lockdown Mode
      vmware_host_lockdown:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        state: absent  

  ####################################################################################################
  ## Manage ESXI Services ############################################################################
  ####################################################################################################

    - name: Set "Direct Console UI" Service On
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: DCUI
        state: present
        service_policy: no

    - name: Set "ESXI Shell" Service Off
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: TSM
        state: absent
        service_policy: off

    - name: Set "SSH" Service Off
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: TSM-SSH
        state: absent
        service_policy: off  

    - name: Set "Load-Based Teaming Daemon" Service On
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: lbtd
        state: present
        service_policy: on

    - name: Set "Active Directory Service" On
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: lwsmd
        state: present
        service_policy: on

    - name: Set "NTP Daemon" Service On
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: ntpd
        state: present
        service_policy: on

    - name: Set "PC/SC Smart Card Daemon" Service Off
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: pcscd
        state: absent
        service_policy: off

    - name: Set "CIM Server" Service Off
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: sfcbd-watchdog
        state: absent
        service_policy: off

    - name: Set "SNMP Server" Service Off
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: snmpd
        state: absent
        service_policy: off

    - name: Set "Syslog Server" Service Off
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: vmsyslogd
        state: present
        service_policy: on

    - name: Set "VMware vCenter Agent" Service on
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: vpxa
        state: present
        service_policy: on

    - name: Set "X.Org Server" Service Off
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        service_name: xorg
        state: absent
        service_policy: off

  ####################################################################################################
  ## Manage Advanced Options #########################################################################
  ####################################################################################################

    - name: Set Advanced Options
      vmware_host_config_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        options:
            "UserVars.ESXiShellInteractiveTimeOut": 900
            "UserVars.ESXiShellTimeOut": 900
            "UserVars.DcuiTimeOut": 600
            "UserVars.SuppressShellWarning": 0
            "Security.AccountLockFailures": 3
            "Security.AccountUnlockTime": 900
            "Security.PasswordQualityControl": "similar=deny retry=3 min=disabled,disabled,disabled,disabled,15"
            "DCUI.Access": "root"
            "Net.BlockGuestBPDU": 1
            "Config.HostAgent.plugins.solo.enableMob": false

  ####################################################################################################
  ## Manage Firewall Rules ###########################################################################
  ####################################################################################################
    - name: Manage Firewall Rules
      vmware_host_firewall_manager:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}"  
        validate_certs: no      
        rules:
          - name: DHCPv6
            enabled: False
          - name: iSCSI
            enabled: False
          - name: snmp 
            enabled: False

  ####################################################################################################
  ## Enable Lockdown Mode ############################################################################
  ####################################################################################################

    - name: Enable Lockdown Mode
      vmware_host_lockdown:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}" 
        validate_certs: no
        state: present  