- hosts: all
  gather_facts: true
  sudo: true    
  tasks:
   - name: Updates Servers via apt-get 
     apt: update_cache=yes
   - name: Upgrade Servers via apt-get
     apt: upgrade=dist
   - name: Reboot Servers
     reboot: