####################################################################################################
## Enable Lockdown Mode ############################################################################
####################################################################################################

    - name: Enable Lockdown Mode
      vmware_host_lockdown:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}" 
#        cluster_name: "{{ vcenter_cluster }}"  ## This is used if running against machine cluster instead of stand alone ESXI 
        validate_certs: no
        state: present  